name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Configure pip
      run: |
        echo "[global]" >> ~/.pip/pip.conf
        echo "index-url = https://pypi.pkg.github.com/susuyummy" >> ~/.pip/pip.conf
        echo "extra-index-url = https://pypi.org/simple" >> ~/.pip/pip.conf
    
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m twine upload --repository-url https://pypi.pkg.github.com/susuyummy dist/* 